server: true
auto: true
exclude: docs README Gemfile Gemfile.lock CNAME
permalink: :pretty

places:
  -
    city: Rio de Janeiro
    time: Toda segunda às 19:30h
    name: Bar Samba Caffé
    address: Rua do Ouvidor, 23, Rio de Janeiro, RJ
    geolocation: -22.902484,-43.175847
    url: http://goo.gl/maps/pBfQR
    twitter_url: https://twitter.com/horaextrario
  -
    city: João Pessoa
    time: Encontros periódicos, acompanhe no twitter
    name: Real Botequim - Mag Shopping
    address: Av. Governador Flávio Ribeiro Coutinho, 115, Manaíra. João Pessoa, PB
    geolocation: -7.097656,-34.833956
    url: http://goo.gl/maps/KrOif
    twitter_url: https://twitter.com/horaextrajp
  -
    city: Salvador
    time: Toda segunda às 18:00h
    name: Café Feito a Grão - mezanino da Livraria Saraiva - Shopping Iguatemi
    address: Av. Tancredo Neves, 148, Caminho das Árvores. Salvador, BA
    geolocation: -12.98113,-38.464165
    url: http://goo.gl/maps/i6Rtk
    twitter_url: https://twitter.com/horaextrassa
  -
    city: Feira de Santana
    time: Toda segunda às 18:30h
    name: Gauchão Lanches
    address: Avenida Getúlio Vargas, 2400, Santa Mônica. Feira de Santana, BA
    geolocation: -12.255637,-38.943765
    url: http://goo.gl/maps/MrVc4  
